In [2]:
import numpy as np
import time
import sys


In [8]:
a=np.array([1,2,3])

In [9]:
a

array([1, 2, 3])

In [10]:
a[0]

1

In [11]:
a[1]

2

In [12]:
l=range(1000)

In [14]:
print(sys.getsizeof(5)*len(l))

28000


In [15]:
array=np.arange(1000)

In [16]:
print(array.size*array.itemsize)

4000


In [35]:
SIZE=1000000

In [36]:
l1=range(SIZE)
l2=range(SIZE)

In [37]:
a1=np.arange(SIZE)

a2=np.arange(SIZE)

In [38]:
start=time.time()

result=[(x+y) for x,y in zip(l1,l2)]

print("Python list took this much time ",(time.time()-start)*1000)

Python list took this much time  258.90135765075684


In [39]:
start=time.time()
result=a1+a2
print("numpy took :  " ,(time.time()-start)*1000)

numpy took :   32.37009048461914


In [40]:
a=np.array([1,2,3])
b=np.array([1,2,3])
c=a+b

In [43]:
c

array([2, 4, 6])

# basic array operations


In [44]:
a=np.array([1,2,3,4])

In [45]:
b=np.array([1,2,3,4])

In [46]:
b[3]

4

In [47]:
c=np.array([[1,2],[5,6],[7,8]])

In [48]:
c.ndim

2

In [49]:
c.itemsize

4

In [51]:
c.dtype

dtype('int32')

In [52]:
c=np.array([[1,2],[5,6],[7,8]],dtype=np.float64)

In [53]:
c.itemsize

8

In [55]:
c.size

6

In [56]:
c


array([[1., 2.],
       [5., 6.],
       [7., 8.]])

In [58]:
c.shape

(3, 2)

In [60]:
d=np.array([[1,2],[3,4],[5,6]],dtype=complex)

In [61]:
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [63]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.zeros((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [67]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [68]:
l=range(5)

In [69]:
l

range(0, 5)

In [70]:
l[0]
l[1]

1

In [71]:
np.arange(1,5)

array([1, 2, 3, 4])

In [73]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [76]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [77]:
np.linspace(1,20,100)

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

In [78]:
c=np.array([[1,2],[5,6],[7,8]])

In [79]:
c.ndim

2

In [80]:
c.shape

(3, 2)

In [81]:
c.reshape(2,3)

array([[1, 2, 5],
       [6, 7, 8]])

In [82]:
c.reshape(6,1)

array([[1],
       [2],
       [5],
       [6],
       [7],
       [8]])

In [83]:
c.ravel()

array([1, 2, 5, 6, 7, 8])

In [84]:
c


array([[1, 2],
       [5, 6],
       [7, 8]])

In [86]:
c.min()

1

In [87]:
c.max()

8

In [88]:
c.sum(axis=0)

array([13, 16])

In [89]:
c.sum(axis=1)

array([ 3, 11, 15])

In [ ]:
np.sqrt(a)

In [3]:
n=[6,7,8]

In [4]:
n[0:2]

[6, 7]

In [5]:
a=np.array([6,7,8])

In [6]:
a[0:2]

array([6, 7])

In [7]:
a[-1]

8

In [8]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])

In [9]:
a


array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [10]:
a[1,1]

2

In [11]:
a[0:2,2]

array([8, 3])

In [12]:
a[-1]

array([9, 3, 2])

In [14]:
a[-1,0:2]

array([9, 3])

In [17]:
a[1:2,1:2]

array([[2]])

In [18]:
a=np.array([[6,7,8],[1,2,3],[4,5,6]])

In [19]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [20]:
for row in a :
    print(row)

[6 7 8]
[1 2 3]
[4 5 6]


In [21]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
4
5
6


In [24]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [25]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [31]:
a=np.arange(30).reshape(2,15)

In [32]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [35]:
r=np.hsplit(a,3)

In [36]:
r[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [37]:
r[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [39]:
r[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [40]:
b=np.arange(30).reshape(2,15)

In [42]:
r=np.vsplit(a,2)

In [43]:
r[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [44]:
r[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [67]:
c=np.arange(12).reshape(3,4)

In [68]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
b=c>3

In [70]:
b

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [71]:
c[b]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
c[b]=-1

In [73]:
c

array([[ 0,  1,  2,  3],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [50]:
b=np.arange(6).reshape(3,2)

In [51]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [57]:
c=b>4

In [58]:
c

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

iterate numpy array using nditer | numpy nditer

In [75]:
import numpy as np

In [77]:
a=np.arange(12).reshape(3,4)

In [79]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [81]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [82]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [83]:
for cell in a.flatten():
    
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [85]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [86]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [87]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [91]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [92]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [94]:
b=np.arange(3,15,4).reshape(3,1)

In [95]:
b

array([[ 3],
       [ 7],
       [11]])

In [96]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
